import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { Root } from "@/components/Root/Root";
import BottomMenu from "@/components/bottom-menu";
import Navbar from "@/components/navbar";
import { LayoutProvider } from "@/context/layout-context";

const pixelify_sans = Pixelify_Sans({
  weight: "400",
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn(pixelify_sans.className)}>
        <LayoutProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={false}
            disableTransitionOnChange
          >
            <Root>
              <Navbar />
              {children}
              <BottomMenu />
            </Root>
          </ThemeProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}
